### ISSUE TITLE
Marking chat events as seen throws server error

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#117]
**Versions**
 - Convergence Version: 1.0.0-rc.5

**Describe the Bug**
When calling `Chat.markSeen(eventNumber)` on the client the following error is thrown on the server:

```
13:07:54 ERROR ChatClientActor - Unexpected error processing chat request MarkChannelEventsSeenRequest(DomainId(convergence,chat-demo),test,DomainUserSessionId(gu,DomainUserId(normal,michael)),58)
com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:63) ~[orientdb-core-3.0.30.jar:3.0.30]
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:326) ~[orientdb-core-3.0.30.jar:3.0.30]
	at com.convergencelabs.convergence.server.datastore.domain.ChatStore.$anonfun$markSeen$2(ChatStore.scala:778) ~[classes/:?]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library.jar:?]
	at scala.util.Try$.apply(Try.scala:213) ~[scala-library.jar:?]
	at com.convergencelabs.convergence.server.datastore.domain.ChatStore.$anonfun$markSeen$1(ChatStore.scala:777) ~[classes/:?]
	at scala.util.Success.flatMap(Try.scala:251) ~[scala-library.jar:?]
	at com.convergencelabs.convergence.server.datastore.domain.ChatStore.markSeen(ChatStore.scala:776) ~[classes/:?]
	at com.convergencelabs.convergence.server.domain.chat.ChatStateManager.onMarkEventsSeen(ChatStateManager.scala:225) ~[classes/:?]
	at com.convergencelabs.convergence.server.domain.chat.ChatMessageProcessor.onMarkEventsSeen(ChatMessageProcessor.scala:127) ~[classes/:?]
	at com.convergencelabs.convergence.server.domain.chat.ChatMessageProcessor.processChatMessage(ChatMessageProcessor.scala:45) ~[classes/:?]
	at com.convergencelabs.convergence.server.domain.chat.ChatActor.$anonfun$processChatMessage$1(ChatActor.scala:112) ~[classes/:?]
	at scala.util.Success.flatMap(Try.scala:251) ~[scala-library.jar:?]
	at com.convergencelabs.convergence.server.domain.chat.ChatActor.com$convergencelabs$convergence$server$domain$chat$ChatActor$$processChatMessage(ChatActor.scala:108) ~[classes/:?]
	at com.convergencelabs.convergence.server.domain.chat.ChatActor$$anonfun$receiveInitialized$1.applyOrElse(ChatActor.scala:88) ~[classes/:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:534) ~[akka-actor_2.12-2.6.4.jar:2.6.4]
	at akka.actor.Actor.aroundReceive$(Actor.scala:532) ~[akka-actor_2.12-2.6.4.jar:2.6.4]
	at com.convergencelabs.convergence.server.actor.ShardedActor.aroundReceive(ShardedActor.scala:36) ~[classes/:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573) [akka-actor_2.12-2.6.4.jar:2.6.4]
	at akka.actor.ActorCell.invoke(ActorCell.scala:543) [akka-actor_2.12-2.6.4.jar:2.6.4]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269) [akka-actor_2.12-2.6.4.jar:2.6.4]
	at akka.dispatch.Mailbox.run(Mailbox.scala:230) [akka-actor_2.12-2.6.4.jar:2.6.4]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242) [akka-actor_2.12-2.6.4.jar:2.6.4]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
```

**Comment by mmacfadden** [comment]
This has been fixed.
