### ISSUE TITLE
REST model PUT wipes out data

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#27]
Been testing the model-specific rest API endpoints.  GET, POST and DELETE work fine with individual models, but the PUT command doesn't seem to overwrite the model's contents properly.  It seems to just wipe it out.

Test command:
```
PUT {{convergenceRestUrl}}/domains/convergence/default/models/created-with-id
{
    "collection": "test",
    "data": {
	"key": "value2"
    }
}
```

The command executes without an error, but subsequent queries result in NullPointerExceptions:
```
15:19:45 ERROR ConvergenceRestApi - Error handling rest call: http://localhost:8081/domains/convergence/default/model-query
java.lang.NullPointerException: null
	at com.convergencelabs.server.datastore.mapper.ODocumentMapper.validateDocumentClass(ODocumentMapper.scala:22) ~[classes/:?]
	at com.convergencelabs.server.datastore.mapper.ODocumentMapper.validateDocumentClass$(ODocumentMapper.scala:21) ~[classes/:?]
	at com.convergencelabs.server.datastore.domain.mapper.ObjectValueMapper$.validateDocumentClass(ObjectValueMapper.scala:19) ~[classes/:?]
	at com.convergencelabs.server.datastore.domain.mapper.ObjectValueMapper$.oDocumentToObjectValue(ObjectValueMapper.scala:39) ~[classes/:?]
	at com.convergencelabs.server.datastore.domain.mapper.ObjectValueMapper$ODocumentToObjectValue$.asObjectValue$extension(ObjectValueMapper.scala:35) ~[classes/:?]
	at com.convergencelabs.server.datastore.domain.ModelStore$.docToModel(ModelStore.scala:75) ~[classes/:?]
	at com.convergencelabs.server.datastore.domain.ModelStore.$anonfun$modelDataQuery$2(ModelStore.scala:298) ~[classes/:?]
	at scala.collection.immutable.List.map(List.scala:286) ~[scala-library-2.12.10.jar:?]
	at com.convergencelabs.server.datastore.domain.ModelStore.$anonfun$modelDataQuery$1(ModelStore.scala:297) ~[classes/:?]
	at scala.util.Success.$anonfun$map$1(Try.scala:255) ~[scala-library-2.12.10.jar:?]
	at scala.util.Success.map(Try.scala:213) ~[scala-library-2.12.10.jar:?]
	at com.convergencelabs.server.datastore.domain.ModelStore.modelDataQuery(ModelStore.scala:295) ~[classes/:?]
```

**Comment by mmacfadden** [comment]
This has been fixed
