### ISSUE TITLE
Exception if Model Query returns a model with no data

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#42]
If you use the ModelService.query() method and a model is returned that has no data (e.g. the root object is `{}`). The following exception is thrown:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.mapObjectValues (/Users/michael/development/convergence/client/convergence-client-javascript/src/main/util/ObjectUtils.ts:27:17)
    at toModelResult (/Users/michael/development/convergence/client/convergence-client-javascript/src/main/model/ModelMessageConverter.ts:173:5)
    at Array.map (<anonymous>)
    at /Users/michael/development/convergence/client/convergence-client-javascript/src/main/model/ModelService.ts:336:68
```

The reason is because the data object will likely be undefined, we be not checking for default values coming from the protocol

**Comment by mmacfadden** [comment]
While looking at this. We should investigate why the data is returned with as `data.fieds`, instead of just `data`.  We should also replace the custom result with the PagedData structure used elsewhere.

**Comment by mmacfadden** [comment]
The "fields" value is a protobuf artifact. totally normal.
