### ISSUE TITLE
Deleting an open model results in several errors

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#7]
There are a few issues that arise. The first on is the following error:

```
ERROR 20:12:42.588 The model with id 'test' was forcefully closed by the server: The model was deleted undefined
```
1. The model is left open locally, and is then forcefully closed, due to the delete.  We should probably close thee model locally before the delete.
2. I do not believe this should be an Error logged the console.  This is probably just event we need to emit.
3. The model id was undefined in the error message.

Then we get this:

```
ERROR 20:12:42.594 Unexpected error closing a model: test Error: the requested model was not open
    at ProtocolConnection_ProtocolConnection.onReply (convergence.global.js:8673)
    at ProtocolConnection_ProtocolConnection.onSocketMessage (convergence.global.js:8622)
    at convergence.global.js:8518
    at SafeSubscriber._next (convergence.global.js:8079)
    at SafeSubscriber.__tryOrUnsub (rxjs.umd.js:831)
    at SafeSubscriber.next (rxjs.umd.js:769)
    at Subscriber._next (rxjs.umd.js:716)
    at Subscriber.next (rxjs.umd.js:693)
    at FilterSubscriber._next (rxjs.umd.js:3555)
    at FilterSubscriber.Subscriber.next (rxjs.umd.js:693)
```

Then we get this:

```
ConvergenceError: Model already closing.
    at RealTimeModel_RealTimeModel._initiateClose (http://localhost:63342/convergence-client-javascript/dist/convergence.global.js:16061:19)
    at RealTimeModel_RealTimeModel._handleLocallyDeleted (http://localhost:63342/convergence-client-javascript/dist/convergence.global.js:16304:14)
    at http://localhost:63342/convergence-client-javascript/dist/convergence.global.js:18031:23
```

Then finally:
```
ERROR 20:12:45.230 Error removing model from offline store undefined
```

**Comment by mmacfadden** [comment]
This has been fixed. The model will now close before initiating the delete.
