### ISSUE TITLE
Convergence JS Client errors while trying to call `removeListeners`

### ISSUE THREAD

**Issue by benjismith** [convergencelabs/convergence-project#84]
- Convergence Version: 1.0.0-rc.5
 - OS: MacOS
 - Browser: NWJS
 - Java Version: n/a

**Describe the Bug**

I'm getting an error (`Cannot read property 'forEach' of undefined`) from the Convergence client in the shutdown sequence of my app. This is on the `convergence-with-shx-backend` branch of the `shaxpir-desktop` repository.

**Step To Reproduce**

First, I create a new user (signup, login, change password, etc)

Then I create some new content... (a book with a chapter, etc.)

I can watch the convergence console to see all those content items correctly sync.

But then when I shut down the app, I get this exception:

```
VM1538 index.html:1 Error in event handler: TypeError: Cannot read property 'forEach' of undefined
    at RealTimeModel.removeListeners (/Users/bsmith/dev/shaxpir/shaxpir-desktop/node_modules/@convergence/convergence/convergence.js:642:23)
    at Array.RealTimeContent.destroy (/Users/bsmith/dev/shaxpir/shaxpir-desktop/app/transpiled/models/rt/content/RealTimeContent.js:20:27)
    at Function.onWindowClosed (/Users/bsmith/dev/shaxpir/shaxpir-desktop/app/transpiled/background/ShutdownSequence.js:31:42)
    at NWWindow.<anonymous> (/Users/bsmith/dev/shaxpir/shaxpir-desktop/app/transpiled/background/ShutdownSequence.js:12:34)
    at onClose (extensions::nw.Window:748:27)
```

**Expected Behavior**

The app should close quietly, with no errors :)

**Comment by mmacfadden** [comment]
@benjismith Thanks for reporting. We have identified the issue and have a fix in test.
